### ISSUE TITLE
How about the performance of pure SSM?

### ISSUE THREAD

**Issue by EricLina** [YuHengsss/VSSD#1]
Dear Yuheng,

Thank you for your excellent work!

I understand that the performance of the hybrid model is definitely very good, but the results of the pure SSM model are also very valuable. What would be the impact on the results of ImageNet1K **if the MSA layers in stage 4 were removed**?

**Comment by YuHengsss** [comment]
Thanks for your interest in our work. When MSA is replaced to NC-SSD in the stage 4, the accuracy drops about 0.2%. You could find the details in the ablation section of our paper.
