### ISSUE TITLE
How about the performance on ImgNet in larger resolution？

### ISSUE THREAD

**Issue by EricLina** [YuHengsss/VSSD#4]
Hello.

I noticed that you dropped mamba's A parameter, which is important to control the max sequence length. I want to know that can VSSD performs better in larger resolution on ImageNet?

Thanks.

**Comment by YuHengsss** [comment]
https://github.com/YuHengsss/VSSD/blob/274e39f1abbcd6ed2e62a3912ba107f061c89e9d/classification/models/mamba2.py#L202

The paramter A is still in usage, you can refer to code above. We are under nips reviewing now, so,  results for images with larger resolution on ImageNet maybe included in two weeks after....

**Comment by EricLina** [comment]
thanks.
