### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by SunHui1216** [YuHengsss/VSSD#6]
Thank you for this wonderful work! When reading the code, I encountered two problems. ①Regarding the Linear layer before B and C in the paper, I couldn't find it in the code. I wonder if it's a drawing error? ②In papers such as Mamba2 and Mamba VMamba, there is usually an activation function behind the Linear layer of the gate controlled branch. May I ask why you did not adopt the same approach as them here?
I look forward to your reply! Thank you!
![image](https://github.com/user-attachments/assets/9ec1d6e9-5572-4e6b-8f8f-8dd9095c89fc)
![image](https://github.com/user-attachments/assets/1218a2ec-02f5-40c9-aa24-ab45dec06591)

**Comment by YuHengsss** [comment]
https://github.com/YuHengsss/VSSD/blob/c0de61d4aca1964ac8b7a310d3647f5020ad5039/classification/models/mamba2.py#L128

**Comment by YuHengsss** [comment]
https://github.com/YuHengsss/VSSD/blob/c0de61d4aca1964ac8b7a310d3647f5020ad5039/classification/models/mamba2.py#L259

**Comment by YuHengsss** [comment]
Thanks for your detailed observations. For the first point, it's indeed a drawing error and I will fix in the revised paper. I sincerely appreciate that you can point it out. For the second question, it's also due to my negligence when changing the mamba block, and I will try the standard architecture and report the corresponding performance in the next few weeks.

Thank you once again. You comment really help us refine our work.

**Comment by YuHengsss** [comment]
Hi @SunHui1216 , I have finished the ablation experiment in a tiny-size model by complementing an activation function for **"Z"**, and the corresponding code is:
`if self.zact: z = self.act(z)`
the act func is defined as:
https://github.com/YuHengsss/VSSD/blob/00f9732a02c2f9ec67392ad44fe7e156edb50e02/classification/models/mamba2.py#L150

I have uploaded the training log in the google drive:
https://drive.google.com/file/d/10Dc5ZIRbzdec0bSmfHnL02niEoRtm7jt/view?usp=drive_link

The results show that the activation of  **"Z"** has minimal impact to the overall accuracy. I will add additional notes in the revised paper for further clarification. 

Thank you once again for your kind reminder.
